### ISSUE TITLE
Crash after checking recipe

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT5-Unofficial#201]
Crash when checking the recipe by NEI with the following mod installed.
This issue didn't occur with GregTech5.09.31.

Crash report:[crash-2019-09-04_02.12.04-client.txt](https://github.com/GTNewHorizons/GT5-Unofficial/files/3570640/crash-2019-09-04_02.12.04-client.txt)

Mod List:
・CodeChickenLib-1.7.10-1.1.3.140-universal
・CodeChickenCore-1.7.10-1.0.7.47-universal
・industrialcraft-2-2.2.828a-experimental
・gregtech-5.09.33.16

**Comment by draknyte1** [comment]
Caused by nulls in an LCR recipe.

**Comment by mitchej123** [comment]
Should put in some null checks to validate recipes earlier.

**Comment by yukieiji** [comment]
I retested with gregtech-5.09.33.22(Build336) and it was not fixed...

**Comment by Dream-Master** [comment]
@draknyte1 @mitchej123 are you able to fix it (pull request) or take a deeper look? Thanks

**Comment by mitchej123** [comment]
I'm putting in some better handling of this, but in the mean time @yukieiji please edit gregtech.cfg and change `B:"debug allow broken recipemap"=false` to true for the time being.  Report back here with what recipe is broken.

I'll see if we can't get some better null handling on recipe creation so it doesn't get this far.

**Comment by yukieiji** [comment]
@mitchej123 Is this recipe broken?
![2019-10-29_17 14 31](https://user-images.githubusercontent.com/40425798/67749203-fded1e00-fa6f-11e9-8f3d-c39b6cde2747.png)

**Comment by mitchej123** [comment]
should be fixed in the latest version.  lmk if it persists

**Comment by yukieiji** [comment]
@mitchej123  it was not fixed(gregtech-5.09.33.23(Build353))
Crash report:[crash-2019-11-19_21.27.24-client.txt](https://github.com/GTNewHorizons/GT5-Unofficial/files/3863775/crash-2019-11-19_21.27.24-client.txt)
![2019-11-19_21 32 42](https://user-images.githubusercontent.com/40425798/69146974-5023db00-0b14-11ea-987b-f2ff5b45e44e.png)

**Comment by Dream-Master** [comment]
@mitchej123  any idea ?

**Comment by mitchej123** [comment]
will take another look

**Comment by Dream-Master** [comment]
i guess this is stale.
Reopen if necessary.

**Comment by yukieiji** [comment]
I tested it with gregtech-5.09.33.48 and it was fixed!
Thank you.
