### ISSUE TITLE
GT6 Style wires/pipes - Follow up items

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT5-Unofficial#68]
- [ ] Always Show Connected - Doesn't allow forced disconnections
- [ ] Solar Panel (covers) now show connected on both sides - look into only showing a connection on the tile entity it's on (wire)

**Comment by Dream-Master** [comment]
@mitchej123 i guess this is fixed ?

**Comment by mitchej123** [comment]
Low priority reminder for me - not fixed, but not really breaking anything.

**Comment by Dream-Master** [comment]
ok

**Comment by Dream-Master** [comment]
@mitchej123 any news here ?

**Comment by mitchej123** [comment]
I've had no time to work on it; nothing game breaking here.

**Comment by Dream-Master** [comment]
Ok thanks for info. Let me know when you got more time for mc. Thanks @mitchej123
